### ISSUE TITLE
Feature: Module power usage information

### ISSUE THREAD

**Issue by dromer** [Polyterative/Patcher#122]
**Is your feature request related to a problem? Please describe.**
Missing information on the power usage per module (+12/-12/+5, total mA)

**Describe the solution you'd like**
Add power specs to the db model and UI.

**Describe alternatives you've considered**
There are none.

**Additional context**
It would also be nice to see the total power usage of a rack or patch with all modules combined.

**Comment by Polyterative** [comment]
hi this feature is planned, I'd like to have it up and running soon. The database plans for this have been traced. Leaving open until done

**Comment by Polyterative** [comment]
#123

**Comment by Polyterative** [comment]
implemented
